apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-topic
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camel-app
spec:
  template:
    spec:
      containers:
      - name: camel-app
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "my-cluster-kafka-bootstrap.kafka:9092"
        - name: KAFKA_TOPIC_NAME
          value: "my-topic"
        - name: KAFKA_CONSUMER_GROUP
          value: "camel-app"
